<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "introductionplus"
 *
 * Auto generated by Extension Builder 2014-07-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[ $_EXTKEY ] = array(
  'title' => 'Introduction plus: Improved usability for the official Introduction Package',
  'description' => 'Introduction Plus improves the usability of the official Introduction Package. '
  . 'You can configure the language menu with the mouse. '
  . 'The main menu can manage upto five levels instead of two levels.'
  ,
  'category' => 'misc',
  'author' => 'Dirk Wildt (Die Netzmacher)',
  'author_email' => 'http://wildt.at.die-netzmacher.de',
  'state' => 'alpha',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.2',
  'constraints' => array(
    'depends' => array(
      'typo3' => '6.2',
    ),
    'conflicts' => array(
    ),
    'suggests' => array(
    ),
  ),
);
