<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "introductionplus"
 *
 * Auto generated by Extension Builder 2014-07-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[ $_EXTKEY ] = array(
  'title' => 'Introduction plus: Features for the official Introduction Package',
  'description' => '15 default bootstrap themes, additional top bar, unlimited menu levels, interfaces for language menus among others.'
  ,
  'category' => 'misc',
  'author' => 'Dirk Wildt (Die Netzmacher)',
  'author_email' => 'http://wildt.at.die-netzmacher.de',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '1.0.0',
  'constraints' => array(
    'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'bootstrap_package' => '6.2.0-6.2.99',
    ),
    'conflicts' => array(
    ),
    'suggests' => array(
    ),
  ),
);
